name: Tests
on: [push]

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependancy
        run: |
          npm install
      - name: Install dependancy
        run: |
          npm test

